baseURL = "/"
languageCode = "ar"
title = "فريدوبيا"

[pagination]
  pagerSize = 10

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

[markup.goldmark.renderer]
unsafe = true
