[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
 HUGO_VERSION = "0.151.1"
  GO_VERSION = "1.23"
  NODE_VERSION = "22"

[context.production.environment]
  HUGO_VERSION = "0.151.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.151.1"
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.151.1"
