backend:
  name: github
  repo: DODYLOVE/fareedopia101
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: posts
    label: التدوينات
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title,  label: العنوان }
      - { name: date,   label: التاريخ, widget: datetime }
      - { name: author, label: الكاتب }
      - { name: tags,   label: الوسوم, widget: list, default: ["عام"] }
      - { name: body,   label: المحتوى, widget: markdown }
