backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

i18n:
  structure: multiple_folders        # content/en, content/ar
  locales: [en, ar]
  default_locale: en

collections:
  - name: "posts"
    label: "Posts"
    i18n: true
    folder: "content/{{locale}}/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title",  label: "Title",                i18n: true }
      - { name: "date",   label: "Date",  widget: datetime }
      - { name: "author", label: "Author",              i18n: true }
      - { name: "tags",   label: "Tags",  widget: list, i18n: true, default: ["عام"] }
      - { name: "body",   label: "Body",  widget: markdown, i18n: true }
